sonar.projectKey=access-all
sonar.projectName=Accessibility Issues Demo
sonar.projectVersion=1.0
sonar.host.url=http://localhost:2610
sonar.token=SONAR_TOKEN_PLACEHOLDER

sonar.sources=.
sonar.exclusions=**/node_modules/**

sonar.javascript.file.suffixes=.js,.jsx
sonar.typescript.file.suffixes=.ts,.tsx
