sonar.projectKey=joe-tingsanchali-sonarsource_accessibility-demo-all-rules
sonar.projectName=Accessibility Issues Demo
sonar.organization=joe-tingsanchali-sonarsource
sonar.region=US
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/node_modules/**

sonar.javascript.file.suffixes=.js,.jsx
sonar.typescript.file.suffixes=.ts,.tsx
